services:
  sqlquiz:
    image: ghcr.io/brentley/sqlquiz:latest
    container_name: sqlquiz
    restart: unless-stopped
    environment:
      - GIT_COMMIT=${GIT_COMMIT:-unknown}
      - BUILD_DATE=${BUILD_DATE:-unknown}
      - VERSION=${VERSION:-1.0.0}
      - FLASK_ENV=production
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - sqlquiz_network
    labels:
      - "com.centurylinklabs.watchtower.scope=sqlquiz"
      - "autoheal=true"
    volumes:
      - sqlquiz_data:/app/data

  watchtower:
    image: containrrr/watchtower
    container_name: sqlquiz-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_HTTP_API_UPDATE=true
      - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_TOKEN}
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_STOPPED=false
      - WATCHTOWER_SCOPE=sqlquiz
      - WATCHTOWER_HTTP_API_METRICS=true
    command: --interval 30 --scope sqlquiz
    networks:
      - sqlquiz_network
    labels:
      - "com.centurylinklabs.watchtower.scope=sqlquiz"
      - "autoheal=true"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/v1/update"]
      interval: 30s
      timeout: 10s
      retries: 3

  autoheal:
    image: willfarrell/autoheal:latest
    container_name: sqlquiz-autoheal
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - AUTOHEAL_CONTAINER_LABEL=autoheal
      - AUTOHEAL_INTERVAL=5
      - AUTOHEAL_START_PERIOD=30
      - AUTOHEAL_DEFAULT_STOP_TIMEOUT=10
    networks:
      - sqlquiz_network
    labels:
      - "com.centurylinklabs.watchtower.scope=sqlquiz"

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: sqlquiz-cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - sqlquiz_network
    labels:
      - "com.centurylinklabs.watchtower.scope=sqlquiz"
      - "autoheal=true"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://sqlquiz:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  sqlquiz_network:
    driver: bridge

volumes:
  sqlquiz_data:
    driver: local